// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '593593260681',
    projectId: 'patientbookingapp-96a29',
    authDomain: 'patientbookingapp-96a29.firebaseapp.com',
    storageBucket: 'patientbookingapp-96a29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkK8g4SWFcLkmbgCXJ3TmWGvqDgmzy76c',
    appId: '1:593593260681:android:e0ca53d92882679c264458',
    messagingSenderId: '593593260681',
    projectId: 'patientbookingapp-96a29',
    storageBucket: 'patientbookingapp-96a29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFdgrZHjAxDS-hk7UCU0t6gUAKqaNMiM',
    appId: '1:593593260681:ios:f2e1de766e2178f1264458',
    messagingSenderId: '593593260681',
    projectId: 'patientbookingapp-96a29',
    storageBucket: 'patientbookingapp-96a29.firebasestorage.app',
    iosBundleId: 'com.bpmc.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFdgrZHjAxDS-hk7UCU0t6gUAKqaNMiM',
    appId: '1:593593260681:ios:f2e1de766e2178f1264458',
    messagingSenderId: '593593260681',
    projectId: 'patientbookingapp-96a29',
    storageBucket: 'patientbookingapp-96a29.firebasestorage.app',
    iosBundleId: 'com.bpmc.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '593593260681',
    projectId: 'patientbookingapp-96a29',
    authDomain: 'patientbookingapp-96a29.firebaseapp.com',
    storageBucket: 'patientbookingapp-96a29.firebasestorage.app',
  );
}
